// Generated by BUCKLESCRIPT VERSION 4.0.3, PLEASE EDIT WITH CARE
'use strict';

var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var TodoApp$ReactTemplate = require("./TodoApp.bs.js");

ReactDOMRe.renderToElementWithId(ReasonReact.element(undefined, undefined, TodoApp$ReactTemplate.make(/* array */[])), "todo-app");

/*  Not a pure module */
