// Generated by BUCKLESCRIPT VERSION 4.0.3, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Js_primitive = require("bs-platform/lib/js/js_primitive.js");

var component = ReasonReact.reducerComponent("Item");

function new_item(name) {
  return /* record */[
          /* id */( String(Math.random()) ),
          /* name */name,
          /* item_state : Todo */0
        ];
}

function demo_items() {
  return /* array */[
          /* record */[
            /* id */( String(Math.random()) ),
            /* name */"Item 1",
            /* item_state : Todo */0
          ],
          /* record */[
            /* id */( String(Math.random()) ),
            /* name */"Item 2",
            /* item_state : Todo */0
          ]
        ];
}

function toggle_state(state) {
  if (state) {
    return /* Todo */0;
  } else {
    return /* Done */1;
  }
}

function setItemRef(theRef, param) {
  param[/* state */1][/* itemRef */1][0] = (theRef == null) ? undefined : Js_primitive.some(theRef);
  return /* () */0;
}

function make(it, _) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */(function (self) {
              var js_set_data = (
       function(el, iid) {
         $(el).data('id', iid);
       }
    );
              return Curry._2(js_set_data, self[/* state */1][/* itemRef */1], self[/* state */1][/* item */0][/* id */0]);
            }),
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (self) {
              var doneIcon = function (item) {
                var match = item[/* item_state */2];
                if (match) {
                  return React.createElement("span", {
                              className: "icon is-small is-right"
                            }, React.createElement("i", {
                                  className: "fas fa-check has-text-success"
                                }));
                } else {
                  return React.createElement("span", undefined);
                }
              };
              return React.createElement("div", {
                          ref: Curry._1(self[/* handle */0], setItemRef),
                          className: "columns"
                        }, React.createElement("div", {
                              className: "control column has-icons-right"
                            }, React.createElement("div", {
                                  className: "button is-fullwidth",
                                  onClick: (function () {
                                      return Curry._1(self[/* send */3], /* ToggleState */0);
                                    })
                                }, React.createElement("span", {
                                      className: "name is-left"
                                    }, self[/* state */1][/* item */0][/* name */1]), doneIcon(self[/* state */1][/* item */0]))), React.createElement("div", {
                              className: "column is-one-fifth state",
                              onClick: (function () {
                                  return Curry._1(self[/* send */3], /* ToggleState */0);
                                })
                            }, self[/* state */1][/* item */0][/* item_state */2] ? "DONE" : "TODO"));
            }),
          /* initialState */(function () {
              return /* record */[
                      /* item */it,
                      /* itemRef : record */[/* contents */undefined]
                    ];
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */(function (action, state) {
              if (action) {
                var init = state[/* item */0];
                return /* Update */Block.__(0, [/* record */[
                            /* item : record */[
                              /* id */init[/* id */0],
                              /* name */action[0],
                              /* item_state */init[/* item_state */2]
                            ],
                            /* itemRef */state[/* itemRef */1]
                          ]]);
              } else {
                var init$1 = state[/* item */0];
                return /* Update */Block.__(0, [/* record */[
                            /* item : record */[
                              /* id */init$1[/* id */0],
                              /* name */init$1[/* name */1],
                              /* item_state */state[/* item */0][/* item_state */2] ? /* Todo */0 : /* Done */1
                            ],
                            /* itemRef */state[/* itemRef */1]
                          ]]);
              }
            }),
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.component = component;
exports.new_item = new_item;
exports.demo_items = demo_items;
exports.toggle_state = toggle_state;
exports.setItemRef = setItemRef;
exports.make = make;
/* component Not a pure module */
